Description: >
 MM@tui.com
Parameters:
 EnvironmentName:
     Description: An environment name that will be prefixed to resource names
     Type: String
Resources:
  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ""
      GroupDescription: "allows http traffic"
      VpcId:
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Value