AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Creates EC2 instance using imports from network.yml
Parameters:
  Port:
    Description: Allowed port form incoming connections
    Type: String
    Default: "3000"
  KeyName:
    Description: Name of key pair
    Type: AWS::EC2::KeyPair::KeyName
    Default: "-"
Resources:
#  EC2SecurityGroup:
#    Type: AWS::EC2::SecurityGroup
#    Properties:
#      GroupName: "ec2-sg-2"
#      GroupDescription:  "Allows ssh and http"
#      VpcId: !ImportValue network-vpc
#      SecurityGroupIngress:
#      - IpProtocol: tcp
#        FromPort: !Ref Port
#        ToPort: !Ref Port
#        CidrIp: 0.0.0.0/0
#      - IpProtocol: tcp
#        FromPort: 22
#        ToPort: 22
#        CidrIp: 0.0.0.0/0
#      SecurityGroupEgress:
#      - IpProtocol: "-1"
#        CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      DisableApiTermination: false
      #ImageId: ami-043097594a7df80ec  # aws
      ImageId: ami-05f7491af5eef733a  #ubuntu
      InstanceType: t3.small
      Monitoring: true
      NetworkInterfaces: 
      - AssociatePublicIpAddress: true
        DeviceIndex: "0"
        GroupSet: 
          - sg-06f4f1a3fec8a0525
        SubnetId: !Select [0, !Split [",", !ImportValue network-PublicSubnets]]
      UserData: !Base64 |
        #!/bin/bash -ex
        # put your script here
      Tags:
        - Key: Name
          Value: Udacity
