# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  job1:
    docker:
      - image: alpine:latest
    steps:
      - run: 
          name: create vars
          command: |
            export VAR1 = $(echo "var1")
            export VAR2 = $(echo "var2") 
  job2:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: output vars
          command: |
            echo $VAR1
            echo $VAR2
workflows:
  welcome:
    jobs:
      - job1
      - job2:
          requires:
            - job1
