# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  job1:
    docker:
      - image: alpine:latest
    shell: /bin/sh -leo pipefail
    environment:
      - BASH_ENV: /etc/profile
    steps:
      - run: 
          name: create vars
          command: |
            #touch $BASH_ENV
            export MM_VAR_1=$(echo "var1")  
            MM_VAR_2=$(echo "var2") 
            echo "export MM_VAR_2=${MM_VAR_2}"  >> $BASH_ENV
            MM_VAR_2_X=$(echo "var2x") 
            echo "export MM_VAR_2_X=$MM_VAR_2_X"  >> $BASH_ENV
      - run:
          name: output vars
          command: |
            echo $MM_VAR_1
            echo $MM_VAR_2
            echo x
            echo $MM_VAR_2_X


workflows:
  welcome:
    jobs:
      - job1

