version: 2.1
jobs:
  job1:
    docker:
    #  - image: alpine:latest
      - image: amazon/aws-cli
    #shell: /bin/sh -leo pipefail
    #environment:
    #  - BASH_ENV: /etc/profile
    steps:
      - run: 
          name: create vars
          command: |
            #touch $BASH_ENV
            export MM_VAR_1=$(echo "var1")  
            MM_VAR_2=$(echo "var2") 
            echo "export MM_VAR_2=${MM_VAR_2}"  >> $BASH_ENV
            MM_VAR_2_X=$(echo "var2x") 
            echo "export MM_VAR_2_X=$MM_VAR_2_X"  >> $BASH_ENV
            BACKEND_IP=1.1.1.1
            BACKEND_URL="http://${BACKEND_IP}:3030"
            echo "export BACKEND_URL=${BACKEND_URL}" >> $BASH_ENV
      - run:
          name: output vars
          command: |
            echo $MM_VAR_1
            echo $MM_VAR_2
            echo x
            echo $MM_VAR_2_X
            echo backend
            echo "API_URL=${BACKEND_URL}" >> 1.txt
            cat 1.txt
      - run:
          name: BACKEND PREPARE
          command: |
            BACKEND_IP=$(curl -H "token: f107c1d2-c00a-4898-bcb1-e014c2892132" --request GET https://api.memstash.io/values/backend_78e466a8-0da8-4df8-90d0-097a39af3741)
            BACKEND_URL="http://${BACKEND_IP}:3030"
            echo "export BACKEND_URL=${BACKEND_URL}" >> $BASH_ENV
      - run:
          name: Setup environment
          command: |
            echo "API_URL=${BACKEND_URL}" >> ".env"
            echo ENVIRONMENT=production > ".env"
            echo NODE_ENV=production >> ".env"
            cat ".env"

workflows:
  welcome:
    jobs:
      - job1

